# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
  schemaDir: '%kernel.project_dir%/assets/schema'

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    bind:
      $schemaDir: '%schemaDir%'

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'

  # ========================================
  # Client Layer
  # ========================================

  OperatorPortal\:
    resource: '../core/OperatorPortal/'
    exclude:
      - '../core/OperatorPortal/DataModel/'
      - '../core/OperatorPortal/Exception/'

  # ========================================
  # Business Logic Layer
  # ========================================

  CrawlerManager\:
    resource: '../core/CrawlerManager/'
    exclude:
      - '../core/CrawlerManager/DataModel/'
      - '../core/CrawlerManager/Exception/'
      - '../core/CrawlerManager/Contract/*Input'
      - '../core/CrawlerManager/Contract/*Output'

  CollectEngine\:
    resource: '../core/CollectEngine/'
    exclude:
      - '../core/CollectEngine/DataModel/'
      - '../core/CollectEngine/Exception/'
      - '../core/CollectEngine/Contract/*Input'
      - '../core/CollectEngine/Contract/*Output'

  CollectEngine\Operation\ExtractOperationResolver:
    arguments:
      $extractors:
        html2json: '@CollectEngine\Operation\Html2JsonExtractOperation'
  CollectEngine\Operation\Html2JsonExtractOperation: ~

  # ========================================
  # Resource Access Layer
  # ========================================

  JobAccess\:
    resource: '../core/JobAccess/'
    exclude:
      - '../core/JobAccess/DataModel/'
      - '../core/JobAccess/Exception/'
      - '../core/JobAccess/Contract/*Input'
      - '../core/JobAccess/Contract/*Output'

  ContentAccess\:
    resource: '../core/ContentAccess/'
    exclude:
      - '../core/ContentAccess/DataModel/'
      - '../core/ContentAccess/Exception/'
      - '../core/ContentAccess/Contract/*Input'
      - '../core/ContentAccess/Contract/*Output'

  # ========================================
  # Resource Access Layer
  # ========================================

  LoggingService\:
    resource: '../core/LoggingService/'

  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones
  ContentAccess\DataAccess\FileContentStore:
    arguments:
      $saveDir: '%kernel.project_dir%/var/data'
